### ISSUE TITLE
cannot load such file -- unicorn/worker_killer (LoadError)

### ISSUE THREAD

**Issue by brobertsaz** [kzk/unicorn-worker-killer#29]
I just installed your gem and pushed to production server.  I get the error message cannot load such file -- unicorn/worker_killer (LoadError) when I try to start my unicorn server.

I have the gem installed and bundled both locally before deploy and verified on the server.

I have in config.ru:
# --- Start of unicorn worker killer code ---

``` ruby
if ENV['RAILS_ENV'] == 'production'
  require 'unicorn/worker_killer'

  max_request_min =  500
  max_request_max =  600

  # Max requests per worker
  use Unicorn::WorkerKiller::MaxRequests, max_request_min, max_request_max

  oom_min = (240) * (1024**2)
  oom_max = (260) * (1024**2)

  # Max memory size (RSS) per worker
  use Unicorn::WorkerKiller::Oom, oom_min, oom_max
end
```
# --- End of unicorn worker killer code ---

I have verified the RAILS_ENV to be production but it is failing on the require 'unicorn/worker_killer'

Any ideas?

**Comment by syedhassan** [comment]
@brobertsaz did you ever resolve this issue? If so how? I am facing this issue for sometime now and I am not sure what's going on.
