### ISSUE TITLE
listen loop error: true can't be coerced into Fixnum (TypeError)

### ISSUE THREAD

**Issue by calvinchso** [kzk/unicorn-worker-killer#49]
Hi,

I'm using Ruby 2.2.1 and Rails 4.1.9 and get this error. Anyone has any idea?

Thanks!

```
E, [2015-04-20T02:20:01.462532 #15679] ERROR -- : listen loop error: true can't be coerced into Fixnum (TypeError)
E, [2015-04-20T02:20:01.462602 #15679] ERROR -- : /opt/dummy/shared/bundle/ruby/2.2.0/gems/unicorn-worker-killer-0.4.3/lib/unicorn/worker_killer.rb:58:in `%'
E, [2015-04-20T02:20:01.462636 #15679] ERROR -- : /opt/dummy/shared/bundle/ruby/2.2.0/gems/unicorn-worker-killer-0.4.3/lib/unicorn/worker_killer.rb:58:in `process_client'
E, [2015-04-20T02:20:01.462681 #15679] ERROR -- : /opt/dummy/shared/bundle/ruby/2.2.0/gems/unicorn-worker-killer-0.4.3/lib/unicorn/worker_killer.rb:92:in `process_client'
E, [2015-04-20T02:20:01.462724 #15679] ERROR -- : /opt/dummy/shared/bundle/ruby/2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:670:in `worker_loop'
E, [2015-04-20T02:20:01.462767 #15679] ERROR -- : /opt/dummy/shared/bundle/ruby/2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:525:in `spawn_missing_workers'
E, [2015-04-20T02:20:01.462809 #15679] ERROR -- : /opt/dummy/shared/bundle/ruby/2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:140:in `start'
E, [2015-04-20T02:20:01.462852 #15679] ERROR -- : /opt/dummy/shared/bundle/ruby/2.2.0/gems/unicorn-4.8.3/bin/unicorn:126:in `<top (required)>'
E, [2015-04-20T02:20:01.462901 #15679] ERROR -- : /opt/dummy/shared/bundle/ruby/2.2.0/bin/unicorn:23:in `load'
E, [2015-04-20T02:20:01.462944 #15679] ERROR -- : /opt/dummy/shared/bundle/ruby/2.2.0/bin/unicorn:23:in `<main>'
```

**Comment by swarzech** [comment]
I am getting this same error can you tell me what you did to fix it?

Thanks!

**Comment by calvinchso** [comment]
I think somehow the documentation isn't updated (I don't 100% remember),
try this config:

# This file is used by Rack-based servers to start the application.

# --- Start of unicorn worker killer code ---

require 'unicorn/worker_killer'

max_request_min = 500
max_request_max = 600

# Max requests per worker
use Unicorn::WorkerKiller::MaxRequests, max_request_min, max_request_max

oom_min = (240) * (1024**2)
oom_max = (260) * (1024**2)

# Max memory size (RSS) per worker
use Unicorn::WorkerKiller::Oom, oom_min, oom_max

# --- End of unicorn worker killer code ---

require ::File.expand_path('../config/environment',  __FILE__)
run Rails.application


Regards,
Calvin So
Chief Technology Officer
Ravenpod.com

Try a NEW and FUN way to communicate!
https://www.wrapLive.com <https://www.wraplive.com/>

**Comment by lowellmower** [comment]
@calvinchso - thanks for this. Your config seems to work, thinking the README might need to be updated.
