### ISSUE TITLE
memory_limit_min and memory_limit_max configuration

### ISSUE THREAD

**Issue by joshnabbott** [kzk/unicorn-worker-killer#72]
This is just a quick question - I've googled this quite a bit and haven't found an answer. In this configuration

`use Unicorn::WorkerKiller::Oom, (192*(1024**2)), (256*(1024**2))`

192 = `memory_limit_min`
256 = `memory_limit_max`

What does the `(1024**2)` represent? Is the `2` the number of processes on the box? I'm running on a 4 core machine, so would I want to change that to `(256*(1024**4))`?

Thanks!

**Comment by TimSpence** [comment]
In this case, `2` is the exponent.  That line of code is converting 192MB to bytes.  There are 1024 bytes in a kilobyte, and 1024 * 1024 or 1048576 (represented as 1024**2 using Ruby's exponent method) bytes in a megabyte.

**Comment by stevendaniels** [comment]
@joshnabbott - It seems like you got your answer, can we close this issue?

**Comment by joshnabbott** [comment]
@stevendaniels yes, thank you!
